export const results = [
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_All_CHILLERS_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_All_CHILLERS_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-03T13:13:40.677Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-03T13:13:40.683Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_All_CHILLERS_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_All_CHILLERS_2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_All_CHILLERS_2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T06:01:49.163Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T06:01:49.170Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_All_CHILLERS_2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_All_CHILLERS_2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_BOILER_OPERATOR_RM_DX_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_BOILER_OPERATOR_RM_DX_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T16:31:02.930Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T16:31:02.937Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_BOILER_OPERATOR_RM_DX_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_BOILER_OPERATOR_RM_DX_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_BOILER_OPERATOR_RM_DX_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_BOILER_OPERATOR_RM_DX_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_CHWP_01",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_CHWP_01",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T06:43:20.397Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T06:43:20.404Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_01/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_01/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_01/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_CHWP_01"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_CHWP_02",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_CHWP_02",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T07:00:54.695Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T07:00:54.714Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_02/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_02/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_02/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_CHWP_02"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_CHWP_03",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_CHWP_03",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T07:18:01.182Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T07:18:01.188Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_03/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_03/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_CHWP_03/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_CHWP_03"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_DIALYSIS_STORE_DX_2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_DIALYSIS_STORE_DX_2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T16:59:10.944Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T16:59:10.950Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_DIALYSIS_STORE_DX_2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_DIALYSIS_STORE_DX_2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_DIALYSIS_STORE_DX_2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_DIALYSIS_STORE_DX_2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_MC4_A_Sec_PUMPS",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_MC4_A_Sec_PUMPS",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-07-31T11:11:17.838Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-07-31T11:11:17.844Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_MC4_A_Sec_PUMPS/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_MC4_A_Sec_PUMPS/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_MC4_A_Sec_PUMPS/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_MC4_A_Sec_PUMPS"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_WS_BIOMEDSTRSPLTAC1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_WS_BIOMEDSTRSPLTAC1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T10:43:48.566Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T10:43:48.572Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_WS_BIOMEDSTRSPLTAC1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_WS_BIOMEDSTRSPLTAC2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_WS_BIOMEDSTRSPLTAC2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T10:55:41.692Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T10:55:41.699Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_BIOMEDSTRSPLTAC2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_WS_BIOMEDSTRSPLTAC2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_WS_CIVILMAINTSPLTAC",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_WS_CIVILMAINTSPLTAC",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-11T05:56:19.476Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-11T05:56:19.481Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_CIVILMAINTSPLTAC/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_CIVILMAINTSPLTAC/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_CIVILMAINTSPLTAC/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_WS_CIVILMAINTSPLTAC"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_WS_ENGRRMSPLTAC1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_WS_ENGRRMSPLTAC1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T11:10:02.617Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T11:10:02.637Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_ENGRRMSPLTAC1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_ENGRRMSPLTAC1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_ENGRRMSPLTAC1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_WS_ENGRRMSPLTAC1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_KKH_WS_MEDCLSTRSPLTAC1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_KKH_WS_MEDCLSTRSPLTAC1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T09:39:15.546Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T09:39:15.553Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_MEDCLSTRSPLTAC1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_MEDCLSTRSPLTAC1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_KKH_WS_MEDCLSTRSPLTAC1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_KKH_WS_MEDCLSTRSPLTAC1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSCC_CHILLER_03",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSCC_CHILLER_03",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T08:22:37.631Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T08:22:37.637Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHILLER_03/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHILLER_03/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHILLER_03/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSCC_CHILLER_03"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSCC_CHWPUMPS",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSCC_CHWPUMPS",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T08:35:11.031Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T08:35:11.037Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHWPUMPS/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHWPUMPS/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_CHWPUMPS/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSCC_CHWPUMPS"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSCC_Chiller_01",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSCC_Chiller_01",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T07:48:53.539Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T07:48:53.546Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_01/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_01/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_01/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSCC_Chiller_01"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSCC_Chiller_02",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSCC_Chiller_02",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T08:08:02.610Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T08:08:02.617Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_02/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_02/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSCC_Chiller_02/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSCC_Chiller_02"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_ELEC_DX_3_DXU_18",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_ELEC_DX_3_DXU_18",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-07-31T12:04:07.251Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-07-31T12:04:07.259Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_3_DXU_18/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_3_DXU_18/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_3_DXU_18/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_ELEC_DX_3_DXU_18"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_ELEC_DX_4_DXU_19",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_ELEC_DX_4_DXU_19",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-03T10:41:01.862Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-03T10:41:01.870Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_4_DXU_19/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_4_DXU_19/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ELEC_DX_4_DXU_19/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_ELEC_DX_4_DXU_19"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF3",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_FACU_SF3",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T13:02:12.244Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T13:02:12.251Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF3/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF3/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF3/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF3"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF4_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_FACU_SF4_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-07T10:12:10.058Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-07T10:12:10.066Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF4_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF4_2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_FACU_SF4_2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T07:52:27.428Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T07:52:27.434Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF4_2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF4_2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF5",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_FACU_SF5",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-04T13:38:29.081Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-04T13:38:29.089Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF5/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF5/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_FACU_SF5/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_FACU_SF5"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_FF1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_FF1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T12:01:38.662Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T12:01:38.668Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_FF1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_FF2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_FF2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T10:41:16.938Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T10:41:16.944Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_FF2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_FF2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_GF1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T12:25:35.654Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T12:25:35.661Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_GF2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-07-31T10:27:29.094Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-07-31T10:27:29.100Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF6",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_GF6",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-07T08:05:19.076Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-07T08:05:19.083Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF6/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF6/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_GF6/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_GF6"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF10",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF10",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T13:30:53.819Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T13:30:53.825Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF10/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF10/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF10/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF10"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF2_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF2_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T05:57:32.000Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T05:57:32.006Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF2_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF2_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF2_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF2_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF3",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF3",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-07T08:42:55.048Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-07T08:42:55.054Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF3/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF3/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF3/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF3"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF4",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF4",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T11:16:44.621Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T11:16:44.626Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF4/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF4/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF4/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF4"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF5",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF5",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T11:38:32.547Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T11:38:32.553Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF5/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF5/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF5/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF5"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF6",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF6",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T13:13:24.337Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T13:13:24.343Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF6/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF6/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF6/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF6"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF7_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF7_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-07T09:56:01.859Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-07T09:56:01.865Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF7_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF7_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF7_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF7_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF8A_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF8A_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T06:50:26.020Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T06:50:26.026Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8A_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8A_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8A_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF8A_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF8B_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF8B_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T07:16:22.318Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T07:16:22.324Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8B_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8B_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF8B_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF8B_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF9",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_PACU_SF9",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-07T07:30:55.172Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-07T07:30:55.191Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF9/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF9/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_PACU_SF9/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_PACU_SF9"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSHC_ROPLANTDX1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSHC_ROPLANTDX1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-10T08:47:16.994Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-10T08:47:17.000Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ROPLANTDX1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ROPLANTDX1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSHC_ROPLANTDX1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSHC_ROPLANTDX1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSSC_SWG_Rm_DX_1",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSSC_SWG_Rm_DX_1",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-05T14:28:45.307Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-05T14:28:45.312Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_1/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_1/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_1/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSSC_SWG_Rm_DX_1"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:PM_PSSC_SWG_Rm_DX_2",
      "typeId": "PROD_KKH_PM",
      "deviceId": "PM_PSSC_SWG_Rm_DX_2",
      "deviceInfo": {},
      "registration": {
        "auth": {
          "id": "a-prod-aegmcwpnxf",
          "type": "app"
        },
        "date": "2025-08-06T12:56:40.686Z"
      },
      "groups": [
        "gw_def_res_grp:prod:PROD_KKH_TYPE:PROD_KKH_GW"
      ],
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-06T12:56:40.692Z"
        }
      },
      "gatewayId": "PROD_KKH_GW",
      "gatewayTypeId": "PROD_KKH_TYPE",
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_2/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_2/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/PM_PSSC_SWG_Rm_DX_2/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:PM_PSSC_SWG_Rm_DX_2"
      }
    },
    {
      "clientId": "d:prod:PROD_KKH_PM:testdevice123",
      "typeId": "PROD_KKH_PM",
      "deviceId": "testdevice123",
      "deviceInfo": {
        "serialNumber": "123",
        "manufacturer": "schnider",
        "model": "Tarshid - KKH",
        "deviceClass": "string",
        "description": "string",
        "fwVersion": "string",
        "hwVersion": "string",
        "descriptiveLocation": "string"
      },
      "metadata": {},
      "registration": {
        "auth": {
          "id": "a-prod-1rvmvvo5qj",
          "type": "app"
        },
        "date": "2025-08-12T11:13:40.745Z"
      },
      "status": {
        "alert": {
          "enabled": false,
          "timestamp": "2025-08-12T11:13:40.745Z"
        }
      },
      "refs": {
        "diag": {
          "logs": "/api/v0002/device/types/PROD_KKH_PM/devices/testdevice123/diag/logs",
          "errorCodes": "/api/v0002/device/types/PROD_KKH_PM/devices/testdevice123/diag/errorCodes"
        },
        "location": "/api/v0002/device/types/PROD_KKH_PM/devices/testdevice123/location",
        "clientState": "/api/v0002/clientconnectionstates/d:prod:PROD_KKH_PM:testdevice123"
      }
    }
  ]

// Extract deviceId from results array and log it


const arr = [
  'PM_KKH_All_CHILLERS_1',
  'PM_KKH_All_CHILLERS_2',
  'PM_KKH_BOILER_OPERATOR_RM_DX_1',
  'PM_KKH_CHWP_01',
  'PM_KKH_CHWP_02',
  'PM_KKH_CHWP_03',
  'PM_KKH_DIALYSIS_STORE_DX_2',
  'PM_KKH_MC4_A_Sec_PUMPS',
  'PM_KKH_WS_BIOMEDSTRSPLTAC1',
  'PM_KKH_WS_BIOMEDSTRSPLTAC2',
  'PM_KKH_WS_CIVILMAINTSPLTAC',
  'PM_KKH_WS_ENGRRMSPLTAC1',
  'PM_KKH_WS_MEDCLSTRSPLTAC1',
  'PM_PSCC_CHILLER_03',
  'PM_PSCC_CHWPUMPS',
  'PM_PSCC_Chiller_01',
  'PM_PSCC_Chiller_02',
  'PM_PSHC_ELEC_DX_3_DXU_18',
  'PM_PSHC_ELEC_DX_4_DXU_19',
  'PM_PSHC_FACU_SF3',
  'PM_PSHC_FACU_SF4_1',
  'PM_PSHC_FACU_SF4_2',
  'PM_PSHC_FACU_SF5',
  'PM_PSHC_PACU_FF1',
  'PM_PSHC_PACU_FF2',
  'PM_PSHC_PACU_GF1',
  'PM_PSHC_PACU_GF2',
  'PM_PSHC_PACU_GF6',
  'PM_PSHC_PACU_SF10',
  'PM_PSHC_PACU_SF2_1',
  'PM_PSHC_PACU_SF3',
  'PM_PSHC_PACU_SF4',
  'PM_PSHC_PACU_SF5',
  'PM_PSHC_PACU_SF6',
  'PM_PSHC_PACU_SF7_1',
  'PM_PSHC_PACU_SF8A_1',
  'PM_PSHC_PACU_SF8B_1',
  'PM_PSHC_PACU_SF9',
  'PM_PSHC_ROPLANTDX1',
  'PM_PSSC_SWG_Rm_DX_1',
  'PM_PSSC_SWG_Rm_DX_2',
]


const deviceIds = arr.length
console.log(deviceIds);